import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "./(components)/navbar";
import Footer from "./(components)/footer";

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
});

const hanson = localFont({
  src: "../../public/Hanson-Bold.otf",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.style} ${hanson.style} antialiased`}>
        <div className=" w-full h-full text-white bg-[#272727] ">
          <div className=" h-24 mx-8 md:mx-12 lg:mx-24">
            <Navbar />
          </div>
          <div className="">{children}</div>
          <div className="">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
